server:
  port: 9090

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: user_service_db
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 514348104125-th0ffk0ro6l1tsfv9bglu76l35b2malg.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
              - https://www.googleapis.com/auth/calendar.readonly  # <--- Add this
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo


jwt:
  secret-key: cr666N7wIV+JHnv78pWtcfAekL4YXd9gbnJMs8SJ9sI=
  expiration-time: 3600000



